apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: observability
type: Opaque
stringData:
  admin-user: "{{ env \"GRAFANA_USER\" }}"
  admin-password: "{{ env \"GRAFANA_PASSWORD\" }}"