apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAg7gQSXe+ove0Z7luyR9GfgowZtu5CVKNpJAQu+EjlxoZbePCuZAg4fjNqHTXTdcE9bAEmrP5/RmRuovgL14XHlR+/SyUKV+unGE+Z8+vlPmNgf6zrX/g9K4v4o1ZHUloHcw/w3n8P1z8EuPxjoHTK30RQ3DKNyer1/SdTihT83BcUzGXfInrIM2uuEI45b14pgaQUOvJF039/34PZdAaYaonQi81O9dE+EJHvb4fQoJn1RO0sZ36rwWMWlklYv6l1RshWT9wFemVpiw8zMGK32mJeqi1SvhKTuntgQLE7jTBqGSqqZkgh0Vneum42IFiA8Cus2r3jHwMDZuPzOQoDwgLmeYOrpPkEBUpvE4AYzxsoJfJ9fOPIdUbWe1MGU616yf9JaiGVPn2JyGxU/1EkV5kLlplUP1lkjL8TMKa2jsJbin1DJCZvUyw53gmBsAQWqOFh4wOS/hmezb2d8BjqNHkxrRbCiosMz2skBaSksh3bI7VEsNkmmkZF1wguL+FXuy3VF2hmKpvMxGYT6a9zN/Jy/cJPhbRV9bTeLAZbsTWQHWJTss+u3YuPIFdP3CjqAqdGViPIQFH/w1Nyzkkl/ubvDu3xovkI9GIXg7b7FKNW6FZsKBl9U/JOqyFJ0zUnXvKsiIYPA2U8Xo8L+J0/1heuEV79QHvc+VskjFlt08ntBE2EJUdpPHnBdePhWiu7GjR9
    admin-user: AgBScrCARW6wFRMMYLLTntQcp0lwkUtP2pCUNT58oXPjAuecDxDE3YqaWeZwSfXE2SHhUBTg4w48gZjnp52skeSKt8GnlbvZ+p6naoG/E8PPYHAYfrn/aBKlOFfN7Hn8DKs7hhH5dGeorC1a/Ws1IlV/XBssrxQhVBAg9CdcYch4DgOMl6FOZx9yAiqLnG8LNwa71WTtIny7kD17+A2N6Kf2j3j9MEIyb8LDf97/dflDXA2zxEtIST/xAoLxNTuph4juEE/IeErklKqDCu23G5ybmwaRJhMTmSSDLqNnWvCqZCGJInff4iJAgv9DUUcH0BvZzlRkDOwBqMux3wsHYWuWTf4p/+tBSDLmSUENShL2HTC1dgwkM+GCJo7YKOnH2OVKd8gq5VKF7+oqxWrlG8VQQ2WUib6E23sWIbV0/TivgS46N8im4xvtM8tpOjtln+F2tGjnAHeSi9IwhZpmWOCG+u868b2OAiDfY17DJSS4WzrnXx/B9t6qHdvlegNKHFHjzuDsBHpRB3brj4ABmbjilkEuN99y2k7M4Hcm9j31vP93rR0YWT0tcQGMpsUx5eMfwvw2aPHUh321iiliTnUwVp6lUIz8qqrKQHoV1vpIhigZbDQ9vA9eH6B8fLoHFfIRPRoQg4SoNqJ6+wFE7gigDxyyEUqYTK0VUM9MnWcI8Rt7kOQ5nCf504HGhLRXCXUvLhAbSg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
