apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-sealed
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBx3vVzOG4H9+NcNbJ+q7+nevs3Rx3X0LuXEo+kuDrvmu/viR8VFL/GgIrthNPIRfPkzh2nxzliH/BSCxH45xKwJ71YKYmZZ/AXMM8tGJGXV99W3aDx0A9ekqj3rhxhHVPMY++cva9qyTr5kG05TjHN/iUAWyCiTMIXCklZv0ApUTWS4PSaxHy+b5wM3zgphwBKlbJLIvHtrkFs2tYjzuCSU9otGLyl9/qWmiD9KAjfUGHXglY24NQ41PiW3wl/QK09gHoW35qYYTZprNdX1jBR34RcjVvCcJPndYE0IDc624Y2pUgpjLqWEAMJkw40Yo6gSjB0iFRs2y9UMwdSaPKXMH/hHCLgItGIoD0V4c1ioIY49yOxQLmioaIPXUWzyV2oN9IDya8W4eNhBMqyzVUz4l0Vv6aJI7BxmWJjjIddcunHmFJBVe1ZclpdZaBOYU/fRzK+TOqlk/KhVlUw63a8wjhXYEF6LXCDvgGYRVThR2cZhCUX6FZdeH8op2f7MaQkIKTjfdf7A3gcSWlcMAljxiq7SjbyvIVXWmGs4gxhMzkM32YB7zsfaf3z+6nUf2V2WpTM3sYLzXyfpxlbjCL43GzFoIHIMrLtYCZXwRxPP7vMikUVmuAkOnzJKEB/hNx4PuK4KON60Tg/lbCztb5w/lFZc5auYXi23esihrmOjLA6Bds5z4rVfUw4pTvNqGREH2de
    admin-user: AgB+6LMRQ47kcjehp1zaDQ+igBioiCXresHOYZPvLjx49DAZF93lPMieyyinPtS933NO6NHr0aYdNgOlafIMNulrYDMzSL5rYzeZm/jM/F4eLqF3n2P2kWpcny3quSM9cwuoYIHbiZHAYWDD4rH33pnBVBbGMv+jYuAy7aI03xLMt9mqP+p0H38VbxlzseBMGKXgsYLI3qRQt1SufAyaqQ5amavVqP4GDami96jmzMDaMbRm93tIjBzP06ErC5TaiDVYQAiXVPznCRGKaXrSBSIvBt9JNYDVNMKGk+uWw9lcAAtQ2nNJzSAEnWvB6fhUy3TMfrAgq2Sv4ZdVvLoNZxld0b4djpPBfFpRBOQEEIp0xyctoZfVPnjYzom2kVfcSdPgnjN6VtMGtW65NQc0ns1FDAikz2Crb0VjoAqHqmnQ6a42F1rMuiIA4/XcfAxUm7LwUp+yqO9AxqIPm5lVeYLyDS7w/QbRyiP7qwRx+TT8cWBaYjE3HV0DOANxvG3FOThUfRSSHer7P1L0bCVgvCmm+6vmvQ01UzEC4aUFGOfZvt0hRWQqCJQarlNvs4O1cNv1GVojf0y9jM61b85Dm+9L47I8MNWyHYZ9IfcKtSTc9PFFSxLfOhHSiJPFz61friJIiKp78ffXMQDcMwuSCTP7mpQPw6S7TLwCpe2EyAk/gQ1+w+QWX3MhiIH+1qGYC0F4gtvAFA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
