apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-sealed
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAMhsmH6ze2D/0+MdhWt8BkudJTda3UlZu+4MjEuFv6Z5wj1Gs00Swa6MZB7XLm7wDi1ohAEOKkdCfgZX3gkCKQqtwK8fZWN4nzsUhQGSVtH3zPQRGqIqhod5ozcNlc2vDwWU8wtbaeBDmMt+TaxQa8R0dsjh5JiEji9gLTXXCBgcepKMMD+MvgkUMQm0yxrausaiBLW7zBxY3aO+iivkRjnI+uHbFM3Lu5bThYubj+uAeAFFskeIn7/RkHvRVfXUgg5npMIMbf1Wsw7tSWqqfFBeAoSJ/7Xkv7zvO6vk1AoGLicU9C43Q3xrnhtXHsbH7QOBzq+458OpkzIF5IizQaYb3wQYhUirVrBxnJTqHCtssu/LKtkkIzWkHAcnzCT1ka5lzh9Gd5tmb20RFFQfcG6MTTNXA7XMEpU+oj0HOEkpPA8CoDATBVn4sBFwSydTHMZWEe/Xu0BVJ0BMQjKBklj+2lbGS5KpruCt8/b/M9s05VTgb8EGs6Wi8njed+LtBsniYTRWtTkuuOezvLCHiMmnvJNGYn64cpDxH6ca+5lfeNoThmUw4MCfxo/kskr5+sTaGA4zX+4Q0jSrNm9n1SSHzt2ynSFC+hpvvz1gi+Nmo2kb5H8Tvf/cd8Gg+d4Sfa0EsUTBkXLTwiVGYG/cBaEHvCny4gGnl03ZdheOtWJnjrPR5d/hMoYtwri0AVBn5sA1Os0UGEZQ==
    admin-user: AgATlEpkdDDiI2v2fHr4YXuWMmhwmQ2il2nuxP4/CpUvltdZ6n/LFwB8kk8Mz0Nz8MwTyjmv1SdGhBqK1N7NemgROEVUU3P0jpeh9nk/wDkWI3MQOlKv6avYpboyDlE+2XsmAHxvete5THgTplMlP9t0hfCeMtDIUWXZlMFoFsh5z/MMfOpuc/yhFFkerQ2D6Ij9bREm9W41UKYkcLtTZi/QpUiYAw0wXFdGtPCK1OIT+xrFcoY6dIUj/5x8qIZ2DSHblBGPzhQZgab01lZ2XxRRxrXRegpfca7Go6143+MK8H6QRebEiU/v9Ju8rSevqQzchtwdLrAEfiIrn4E7hT6nVJHKqLjrySGESbaYylal/XoOaCfM+fPmCtBVYSnEhD183UXsIDI7/zmAJYAB4t+M7k+87XvfQEtDS2UENyQt8zof0Anx+IZ09n9rQUgGNkTw8MJeAfwa7Aa34CDjBAuYIC1FdaEEJq1AF4tzRIiQs0dpL8by9N52wvKHz0tUHJNMA8e7Nl99CsqYiIgkKhsH1TZDGF7KYA5tUdLZSHArA0mkqxakHLC9J6jOXQR4wIuwYERwbKaRl4laGbwkTOmtxIe+8AUkr3VxZdPb+4kJjG3TxC8iH9fDzz+SwmiVrLi1ZaRitCKZpAN1/96qXqwpkN+ng0fc/IU/SCmVhG+TeqWyq41YbSa5Y2iA88h1klxP7as6gA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
