apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-sealed
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAQL26i1c6S8aVb0YsTESRHSjuMCJzxvJPLF3K7Kyjf1jDtLWf2ZxLc6q8wH1IQ3RTgtzdwzraK+n0quIN04lOCz/Hhjp9wvY2lxRN5A/UD0rDmOSmcJMNfUD2sNeL+OitZ6Z5GvGcS3mHuJJyEsrL+leR2+/CGKef+L6UWH+mwfnMTdLH8XdygVgdqICvs8JfzxBrVVCwuoJLUcE6Gk8AKJff3ViUWOtE1DrFeStMCQ4Dk8QRWvG3tP1lmTzu+bGDjrpntz9Gb34rG0bds5p7JbsAIsnetop2Z/gKbCt67XRunjPY02dhPer4CFB22S0n4uzaORaHfJhVd0GPzLLAnt3/+H0nZo4DL6uHNMNCWCWnTGniEhmV1V76qa9sT7LxEUXbxp/woGkme+tPns6kda4iS5vfJjrJlNg6Zqx96cOvWirw67KPMetT6pRdyO3R1QYlG8w87GMhz1eTaZiCKDD51BHpPZzaRand70blYFHpt1Am1EI3IMJ/m/b7xdvIBWpVfKi3IyZuLEfpR0mIHZ1Mvcdzgx9zqHhPTIZLQA98KgjeqMJNKkosGrO35XcA9kyvG6A0X/wcEdJQcNHU2M/S5rPiSPmkoIKoNRUX8c8gQoLgBrwcYn8qewmvkolKi/OyOt7Nhx8ACX5b46J4Sh0ZmV5xKaU1g7zmYliKIBGQFkxs0Y1tktg1UPVt+vHM9coR+35yopg==
    admin-user: AgBxUxwpYPt/CU9Pq/MxeononSnfIlqI+VS+HvmbacqjMo+sxggN9E1eJRGRNnpaH34ORdIf6AGTSiLdZBH/d8uUaS9cxIhZzarP/tFma0s9U3mvi6IDLW6RgWXVf27pnU/Bl4GtODbfPq9qCh5a0CYy38INd15Yt6WU45HQvhKThnojyDC9Z+SQUp+CNeBZoETtKq3flTZiL3EOSNjZj9Qp7oVhNgMgTXESC/9qvNcSgtFvhwIlBdbH+MPW4uKO/JbD/sit7krrT7FJB2S4/wCl1E3PL3I8kAqNRTQBa4+UG1Swzv5vIpXGOyeaPWIUeiSb4y1j3FLRBL+7wdYPn8OIxEQGBPJFJyI0UdcDU7Scz+jyBMe3ztS4+N2IqBf+zVlt3PGi+zjXYsTKSwwq9hVtNbAqtGztncIFNrgO/oIMk+qjS7mGUrHL30MlFQZvXxkmsKbEJLcqvcVQNXnnkREzUTLAet0prNGnoFtAtMNI5yyW+G5wA0uFzpITgJTqlxFB2Mkno+kxI5WFol5x5LwfToaImXCGXdpzhKbd1Am7zGLme4XAcQwFJDk9siR4plFZIR0RsTQFDsExaOyIKTkMlXETTlxMc5t6i7gu9cBCOk2OEr1zy7UD1/2WC1yRqyVIB+P8xeYvL51hUzRPOObRpDADDvscGhvVqnEMlZd0p3BZqFQRq9QU25tRKLTjDpF03AYM5w==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
