apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-sealed
  namespace: observability
spec:
  encryptedData:
    admin-password: AgA8VVOw3/lo/yTPYA3iMJlJGcNInxAqMq019FFwKJqXspu59je0ActPnw4px/c41TB8lf/zRFvf2T+N13iszNLiyIN2zr9A3syR671rNq/n7uaMdPuK8Yc5nsRZ8w5hWeKc/NS5zQgXKFoTwlohxxN9bW5Uqe6PPqkWzbLtyBDyq+MMZ8qg5pfdGT3O68H2HGhDeLOiahxvAoJ7oBiAqdoj+hXq6U+AnIctFl12MoRd1XAjgkHzqPJPM/s/oro1nZLb2EsWArtgFpU/JLlrK1sOIBSX7Cnf1ruAnRotQUSq6gOho7HKd/ijjnH9WkY4VfHB20ciXmHGJk9qrv/Tc1ReaQNliLbod2rk1DV/WnJESBUhkcj/3HDav1Iy5HrO9poO68YBQCgE1OKK13z0oXzp4xuxgcv8pwKB3pkOWsTc9ceyzH2Zgocm1Oj/tjydgEAFQBcSq8RpU04brA+sT8ACm2MpLlPh9DcbTbISYHIyhw5cFX572JnUVL2IuEINfvOj40aTnP4bCddnkm2oxgyVw4KSAvF9czSOIgxvY4RFnLY25F9tHbTjPW6FXQ6ikImkgRMYeqwQdftKYXmNL591ZegjchP7068R0Qi4CKU3MbQNfE4OQpcpdi6l8rDv+YExQz5JOCXtMFLGpD2F39+LZ1pdkmKW6qQi1bXntPVls2AreSqeKyztp6JZ130JejOdz9QRN0ZMvA==
    admin-user: AgDBRw51IXs+RhcMk6NOFiP1SpOhcTvpftKr5kAixp5YxRJjsd3AeS8jo35D3gtgVLkF3ZizY+a07/cU9L89QHycDpx/MqhalzOAYt78V+aGwPtqO3eCp2oG1Q9cGF3Ql2dXYJlxwVg2qjcs9vMQ9Mp147PRW7uLwcDr06mXseYoG8gp93VAgwm8oT7ohJWtlMVjdPzqK0I2tSP2lkICp40Ky2sVZpU6RiJWXsoO9c288i8V3gBI64kfPWI52AoVgsdF5TRbASd3hsSq7lN/2aTHgg2DzfcM+LnacUov/eu8g/7RDUh8yBE3P0LsVbs4Rq48rnkQqXNs38UUXcG/5lKi4Yd6/t73HLZSGM9N4kCHBgTz6mlFkKU4qtUfpztivrwI0BtYU8iBMOK2r3cofYR/HRfLYvWHhAouOnJYDs4wkW5/2s5Am2B+pcUQFIImGwAngzsFeJLO1TIsbkVw1yBd7INBUJ/8tCKYcizKOUmviwTv8SBOKNtdBkEWmchBlSfTUjjx3BWEH2QV/2cmOLw6PRPTR5383raM98aA1Z6wptm9W4IpyukEy1dBi68tqwEp6JPYpTsRzseSUHDZ801Bn0y4qfiFoTx7Zt51Bzu2iOuW7RL/6UwKXRl12I6UlRQV2/mmC9r7D6e1uCJyniVySaV57jm6lyLXJFyS0wq+kkH/cF3z6NNeqXvikKEFahaWhjPabQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
