apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgB22MBpsp8Zw7E2sDOx3o3adoJqt+uFxz3Xt0M2gigylUrYYJ4gv0G8RKVsSJI2p37YJCZl8bq8x0yzBGenB07TjNo6fq+5q6XBsv9Swax2x8kB0XrXXpR8eUKDLb2aCZ6Xzx1wTxZHaNDanbRrvKGRLRCYi8Dxin6BPqFxehnbCcqDMWcIKUCJLELZO2GUBen3XBlMDI6+1g7mVnKAGBlRK4r3o8HxFlKYnkAB7iJjT24NZrE0XHNPPw02ordAhz8KOBAeQADZzqYDWF1qrxuP8Nar8RxmpBgX9KyYtbNeOVbrioNDUl0sGXIoDDG7zaMetjLzVRWXUg8Xa+4btDyykIylZqFF1wSFPTJMBYAU1wrMuKqh2rKyU/PSCJXLMcSINVWapwuSsbsh/dC8GTe9KkNxhqHZaKpDAiyKGLpbpAoV1VF+7wA9SzvLCbtsMZ6OvNAP5uPgenjLvo/DZ6SuVgNq3vE8htbhiT3F7PBdI+ASoEt/IDWwu4ghGDrqveK90yz2B+zdiwO4WVGRCMcemZY8KOTYYO2R1HkYpKabxtcS9PiyhHI18KpAzA+NnJzvICJyoqeER+eiZV1ayjPgKXoyP5y6tQntvj4QlUPSVTBiiVE1szvKMHZkK0DakS6EYCgwg6tCFkb/sXkRYGGjsyDYQfyh0QyykWCCTW+8IPYaBJFOQO1/KmbDsYNcG8ZYuQV6
    admin-user: AgC0+Tf8nprLOjn44BnUSkHOwNSAEl48xUDGTc04VNI/HhX7w9RXCSwVCeMB2ejUVXTNINYFPdyv6qy7LoYR3nm3D+DSUuP2eCleqsLy1HG0dmpXhJwochWRx9a6rPU4iFYCIfl0cXOOjfmd4xiym3HXRNyQn+QPOPQXPzfa3IbZZNWa81RI23YtYWJWtOPZORgSCcGFmwm7Mx+jMVwjMt1zi5Be5OhlErJMS2fmsYktvzC69UE/4Z2lL6ysjAj+dmrfDnqnh85EOnCiThQ9NigatrDxdhi0z68Rjshv77AgOQ40Ik7zR4ISZ5Ni+pRi8EuhgI8Z3FUjisl1ATmj5HqgVsjh5geE0xZhTEuqBAcGj73UllQ1JjPLjzZaDjYg3Pu4/rFA0iWyDUaGfHKblUH2c3yT5fQJkiByUYfxrM2E7AJ95OMN1o+L0GWIue4ygSsBg8zgrFQEpt0f8jULmp06HMCjVp8S8yT+HhINP7mNwxkWiH+X3d8+bzHY1F65vqQI8GJS8qK6U3VeosETph1SIMwLIPkIFAZK9CdaMsvvZ36sw/77VpJe/0AIcH74Jh0GxTZw7sKcmdI6ZbsSAmFKPyyJU2gRglQhD+UM1OYymOq09nM6D5M4Wkv+L0jP0rFPklLgcrz3fDwsf6rNgBPDq0y/6jKl0SNqD//3nF2BUsue3HVUHkWlNEcM/7e9HBHcpOOrVg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
      annotations:
        sealedsecrets:
          bitnami:
            com/managed: "true"
