apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-sealed
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCMPAMo0ekZQGeLoUAgBPGKKWEee3QHi3cWQh5o19BZsPYdtheCiZIWkqIsWs0Z1/8RcZDoMARCJLsamUHYDJ2tTzlpoyz1IF59MbqLfo7AYFhOinzzt+kj1nCqKFgDAwV7NpwbL7HZacvtwZloUcK59F5LPecJtdkbQfgmqyPrbdZ4Zrgk/rWRJLs1ZXtAEgh6hBbLxS6bZPAwshj/hxrY5mww9PvjhQX+3NHFV8pBNpEQHc8asXHqS0tf6wuAclOx2YG9SmsDQ0RGmeubbmrC9Lzxj35MubfdX9fdBGkXg9MCuO/orkW4k7c4jQzXFkxF4mF51JtfXD7RrPzxizT/2rNLxnzXOPRXBXSuV19HtuZxWY4rfpj97x+5g2kwefWlXbdpeMAiYrKqMXnXY1JiGThfLYPsSYdW/3372NS2t4+g5GhBEbJpPTese1RXLtVtcWhUiDVjxMBDhVYmoH1UEn0tGN5HP8LIzyOvjYykFnTbkySrGlYIhx10vJFTKxdQcdjzO1ZX5ARegZfNbU1JgOSI0E68wh9IdWobO4a6h4S8Xwuoan+8Kh1ACwXJJ50PU3bVnWJz8rwcfBDhRSos5W+yqJhmTs1BMedymVCi6sg5+1Ol4gbmwLcraMgF7IcjlmcqqyoyyobE2sNPZCRh/m7sI0mC7h2CLo5uJBa71eCXxG+ulqqCCfVuF7Mkt5eMjW8Y
    admin-user: AgBj74Jfxa6g0Ue7urbfO6lyDKveKRV+0DJ6K/Hpl89mu3HBmgIgguflJekk5FjQbK1uOyrQPn4GUeRdfwT4MsiGIvdeEddtyJYdwfi6qML9w20rBQ4fGwWZHaQp2yRVw8njp4TddiKPgbSE+czaWdvOKw0OMN4fiNthdlGnOQwJ1D/91yfCQJW3sTycVZ02eUU6ZgnfsKASDDjIcPBPIGJaIRXVzUduyuSn4vVPI5lmTQre/Z6S1FMzKGY9Xmdpgdas6xBb6aVfFsddc4JHeIENqOZs3ImMd+qoSYe979Tf4ofsbL12Ek3L5GIVJuDrCb9p3MhU/r+Zozgo5PtyuRioK5AOv2c1clbhkZ/hQG/TgTkXclXSaHJxj+JwtEy+5CSuZfwB6GvheCqhztiop5uwWjgym79Eo77Jo0FIePIwJocGXkogv6MAflP+av21+4cfL49Q63iCr/U2yf/vvXnTGWG3+AsdXVjtCkskehuOOGdamS2LaMHIZKri6pXerdLEJZJvMCE529efXfgfIY5lMLX6lTR1MSqNq8iMSD8CSHuhATD7tZieGSZdWcDc5BGmehuqrfNIWIvPqQOlnfk3TFzhO3SfxYHUNUMezqx9bfwfp4nwICXjQwoXVpryHR0kpKttcP+Rx8GR9OKXjm5lI2/pH+xzOhRWXw2Cc3Nq88BII0cxhTpqff9vOlMSbrBquJBFUQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
