apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-config
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  {{ .Values.env.configMapKey }}: {{ .Values.env.APP_ENV | quote }}