apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-master-credentials
  namespace: observability
spec:
  encryptedData:
    password: AgBEUAr5kjiBBwwhZs6Mbh7wJLKNfVdEecwJr5wq5MBimzIY3ZVbxh62VVbnzg4VmVaMGFCXveZDpA3HrdNOBx1ng6uyh9LY+2AMf5b2nv0/nBc1BQC3RQ0W78B/Mv+Y+5bePGLHY5VWe2S+qblMAt03uUX0c8cs3kOubtk3cy7ACWO/Hujfqa6RzWWclQMdJFRfmOkQPUG9E4u+uDvgOxVhFQ+Klxuk2DOb7xG9pdmlYrx5t93oNJW/1pj3w/WcupNoBcXPUdGsTCJx2Q4MAjHYGfpufUjUZ/l1XNDKYfphAVcLoi2/n/nFAXm06P1baNoPqUeImv1r7WYxQahlwnh1fIpRsRfhgnJXUrud0i0PWj0BYyowqWo/EWq5arYsUdPyMtYzHl0fcPrR73BMinp6vp0JpoV++bl4m1jOIxxSWIYpLLy1AnFIaXFFSvgry4SvljrNSpe3eY4oHZccq57PDl/SO1WgLHEQiSSpmFTq+1j8/f3sLXoGgjIFBOAhMfbhtcuShrnSCUYl0z8SX8FE4qvacrLXIY2V3zJxgzADXN3k/Fq/7x3pyJaMJbk7Bk76mExIm75lxP8Jj9yYHf6WjajfSm8aks8BrSKNonEbRv/Q3Pb9rMlQttMrShew9AvQt4Tvgo4W9/+GT4gkV2uXF5hdDvDlU06WSmC6NLGoJmFiC8hRDJBNR07T1xED1+Md8iuvtUDa3w==
    username: AgBPkwgCXkETJIl/a2RLoRWu6wiGv/Zx6cb9OhENg3b47jNuM7BRcoioBP6useVBv9jWSueA0JD9elZt8oysDTMvC/brl5/8k9RUbsaweUiRbX7kwhAr+a0rzAN1HJt9Yx6VtDxQmAGkNQNCwt9DTOxYrq5emqdfh8HxM/U+tMabHlNRojC8IuITIcWOAZ741j+KrQwBT5lVMYaU+m62I0c4SigfAJtpYPGGLwJwJAEat/wFBSgW9QNGm6U2eMu6y3HZbYQtUgWvXzdLwfF3NCgeEwRa7KOcGEwD+aABFk/9N4sX8FyWnak67RaVY0QvBIEW6hSjz8qZbiB4XoFYS/eDl+NGWp+vDx5oYfxWvA8IbXs8zK/yGnMJnZc9X1EVS1vtuPe4D+uB6uuySm7AAeUlKxVqqjgRi5zQ+sa9Nf3E3aEJo6oaXHYJL/KJlGNAj1aIgWtzJ+KlUKhl1qn0hWFxhp8PAn4okcwE9fGpPYqOWAU4VeH5XxuEAxotF01OxrPZEa5fhgHP6XwEvwpFuAzUcwBCPWarLEdbN9sMLmhQqOCRMpdBHqRPHgTIGywuB8Mz4UW0vVOBCC52/566DsmhGoqw0ar25iMITkeFEiSz6u3Kd/XNdQPyhChUzACMX/NePGUzUh66tJTE89NnG0Hk7h2JwtyWzZO12mvZOM8BMG62HXgnkhq7xfuuHewgW/ILWXzOxKNH
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-master-credentials
      namespace: observability
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
