apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-admin
  namespace: observability
spec:
  encryptedData:
    password: AgCdAHzTWjvNhk3k+iebfPcYQMW9nadC4YndB1XutPV860cIQMlThMcEk1bnARyufu7R0xQWiPd/RDPAy8xFriiPrUEUHsbcPIDmdnoeWOPCiojCxE0VblBDNat2pSYV9SdPuzSd/Pwi60KNdqqBz0FpXzNpQpqHEFNridcX9YV4apDWTHSAzLJJhGqZikDAvSpxMC2ZBXu0xpHAfm07JHwdkm+3AVKyUrfO41CIxT42/dFVhHxuprrbPj7+d1VmdSA50nXvWUOZ6HYQfAjIGAS8j8o8hANJ4VsysTzXr5xTiLhvuMUY1qhYB3Dk3stwP6OrJpklyBorwh7I22UOhxIx4758al8cv9ph/xgdHR6QOb/avFxsZjuZuxNbiaxVyx/ZJb2WsVZXVoB+MwQUo0LPxN/DRT/BJ80Ecy/UsPB4qJcR6nanNqothtaIE4wtRqTQdzjHFXYdT6WZ4sevh5FAfA72aFqqJK538y/hAawRCydxUwu3tpPpLvr+ULCyxbbFVD1vzfNeZSWGz+M+ZSICCv0oy/EDm/PT8rGBaaWjS/raHVqYS83tg2ShIyykr6Mw2YF7zBvI3JHnxDyuDEO9s8iRYYoZpIQn6gRPPwnuD5ipSBqlIa3GYugLT8+1VAzcq2ZbOebL2oP2k0XYdey+farH2XWUZQBGd6014N4zB63vsFRIsTRYb9sLtiyYIUfZq9N6+VkzCw==
    username: AgBj7TUS1yG1iGO3DWNsp6PHcwV2MC/8rS1wQ+2AN/MVlwdktB4lln3D7+/LjYNgPVt4dA/bLEQEBOkCu0ds7UtIBK0uk9tffgXpXKl5EaR/og7wUdf9ZrCzTMuC1uXZu0YQ/cG+Z/MfhjutRWCJ2l4wqFxJ2Ze8IZAsBVSt5Lfi28K5QkMSyjL/ybQuzEuaGu5I5CEQEH6yY0JFUh4yZ57zZpkkrar1QsIcp7lDR8VtcvfFEmkplSyFjIoIBY0IzpV/947n+71Maw9L0K1qgJnFkQLhRNuyfGzowikLpQC3m8xPqSvND4nf2wFNdjHuVEV9WL3uxcLwRd6eoQux4cuHfj3CNhCPJqQPRPzcj1O20tb1Mmnq25/Nd5vaN0eYQrPy6TJ3Z/E96jYCZDFDvhWPjK+NfeRG9wEpLIXziA2cNEp3gtZfOEDHvJZsqOzA4kKCKjA6hEWSEOd5IY0DCLw76AIoRmNl2kvZHg8J/stMkfQ4hjNpNsHNPM+g1DcHJcWrH1dp7+YCGqEVnVPHZFoyShFdhYdvVEm2E6bhj2FbrBciYhzrAW3Kob6LeImn6fCG9HatUUVNTAb+RyYAASK5c0OWL8XkwTUKue2Yyiy2xcd1hcpLMyagMtp4rv1N7kNXgdO0AKB1keEie+ihBZFzqDB3TMnMBdMiGEIzvusLWRwHnwWrCtI8yux0y44CjwkHBqhgIzUb
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-admin
      namespace: observability

