name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login usando Secret para o Usuário e para o Token
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build e Push usando o Secret do Usuário no nome da imagem
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sre-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sre-app:${{ github.sha }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_DATA" | base64 -d > ~/.kube/config
          
          # Garante o Namespace via variável (ou Secret se preferir)
          kubectl create namespace sre-test --dry-run=client -o yaml | kubectl apply -f -
          
          # Injeção dinâmica do repositório via linha de comando
          helm upgrade --install sre-app ./charts/my-app \
            --namespace sre-test \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/sre-app \
            --set image.tag=${{ github.sha }} \
            --wait