name: SRE Pipeline

on:
  push:
    branches: [ main ]

env:
  K8S_NAMESPACE: sre-test
  HELM_RELEASE_NAME: sre-app
  CHART_PATH: ./helm

jobs:
  lint:
    runs-on: self-hosted # Usando o seu runner local
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Dockerfile Lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

  build-and-deploy:
    needs: lint # Garante que o build s√≥ comece se o lint passar
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sre-app:1.${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/sre-app:latest

      - name: Install Helmfile
        run: |
          chmod +x ./scripts/install-helmfile.sh
          ./scripts/install-helmfile.sh

      - name: Deploy with Helmfile
        run: helmfile apply --suppress-secrets
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          IMAGE_TAG: ${{ github.run_number }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}